[Fix]:se realizan las modificaciones para que al editar la Pet, no se…
JuaniLezcano/vetsoft pull request #13
Opened 2024-06-01 14:39 UTC by ValentinMilocco

Anteriormente a la hora de editar el pet, el campo de birthday aparecia vacio, realice las modificaciones en los archivos pertinenes para que esto ya no suceda.

2024-06-02 21:39 UTC, Rafaegur commented
No me funciona el test de e2e en mi local.

2024-06-03 17:50 UTC, BenjaminPeres596 commented
No me funcionan 2 tests de unidad, es por cambio realizados en el update_pet

2024-06-03 18:28 UTC, BenjaminPeres596 requested changes

2024-06-03 18:28 UTC, BenjaminPeres596 commented on app/models.py
>      def update_pet(self, pet_data):
Habria que modificar el update_pet, hacer la validacion de birthday, nombre y raza aca, porque de otra manera el test de unidad y de integracion se rompe.

2024-06-03 18:28 UTC, BenjaminPeres596 commented on app/views.py
>  def pets_form(request, id=None):
Modificar devuelta el pets_form para que la redireccion del test de integracion funcione correctamente.

2024-06-03 23:55 UTC, BenjaminPeres596 commented on app/tests_unit.py
> +    def test_update_pet_with_errora(self):
Estaria bueno poner un nombre de test mas concreto acerca de que es lo que se esta testeando

2024-06-03 23:55 UTC, BenjaminPeres596 commented on app/tests_unit.py
> +    def test_update_pet_with_errorb(self):
Estaria bueno poner un nombre de test mas concreto acerca de que es lo que se esta testeando

2024-06-03 23:59 UTC, BenjaminPeres596 approved these changes
Deje unas recomendaciones acerca de los nombres de los tests. De cualquiera manera funciona todo correcto, por eso apruebo el pr.

2024-06-04 21:36 UTC, JuaniLezcano approved these changes

2024-06-05 03:23 UTC, merged