Agrego tests especificos de Address en Provider
JuaniLezcano/vetsoft pull request #23
Opened 2024-06-02 18:40 UTC by PeresValentin

Correcciones realizadas.

2024-06-03 19:02 UTC, BenjaminPeres596 approved these changes

2024-06-03 21:52 UTC, JuaniLezcano commented on functional_tests/tests.py
> +    def test_should_be_able_to_edit_a_client(self):
Con este test se esta editando un proveedor, no un cliente.

2024-06-03 22:01 UTC, JuaniLezcano requested changes
Los tests se ejecutan correctamente, solo resta modificar el nombre de la función ya especificada.

2024-06-04 19:16 UTC, JuaniLezcano approved these changes

2024-06-05 15:24 UTC, merged